export const engineeringDepartments = [
    "Computer Science and Engineering",
    "Information Technology",
    "Artificial Intelligence and Data Science",
    "Artificial Intelligence and Machine Learning",
    "Electronics and Communication Engineering",
    "Electrical Engineering",
    "Electrical and Electronics Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biotechnology",
    "Biomedical Engineering",
    "Instrumentation Engineering",
    "Industrial Engineering",
    "Production Engineering",
    "Metallurgical and Materials Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Mechatronics Engineering",
    "Environmental Engineering",
];

export const institutions = [
    "IIT Kharagpur",
    "IIT Bombay",
    "IIT Madras",
    "IIT Kanpur",
    "IIT Delhi",
    "IIT Guwahati",
    "IIT Roorkee",
    "IIT Hyderabad",
    "IIT (BHU) Varanasi",
    "IIT Indore",
    "IIT Mandi",
    "IIT Ropar",
    "IIT Patna",
    "IIT Gandhinagar",
    "IIT Bhubaneswar",
    "IIT Jodhpur",
    "IIT Tirupati",
    "IIT Palakkad",
    "IIT Bhilai",
    "IIT Goa",
    "IIT Jammu",
    "IIT Dharwad",
    "IIT Dhanbad (ISM)",
    "NIT Trichy",
    "NIT Surathkal",
    "NIT Warangal",
    "NIT Rourkela",
    "NIT Calicut",
    "NIT Durgapur",
    "NIT Silchar",
    "NIT Hamirpur",
    "NIT Meghalaya",
    "NIT Agartala",
    "NIT Jalandhar",
    "NIT Patna",
    "NIT Raipur",
    "NIT Srinagar",
    "NIT Kurukshetra",
    "NIT Jamshedpur",
    "NIT Goa",
    "NIT Manipur",
    "NIT Mizoram",
    "NIT Nagaland",
    "NIT Puducherry",
    "NIT Sikkim",
    "NIT Uttarakhand",
    "NIT Arunachal Pradesh",
    "VNIT Nagpur",
    "SVNIT Surat",
    "MNIT Jaipur",
    "MNNIT Allahabad",
    "MANIT Bhopal",
    "NIT Delhi",
    "NIT Andhra Pradesh",
    "IIIT Hyderabad",
    "IIIT Bangalore",
    "IIIT Delhi",
    "IIIT Allahabad",
    "ABV-IIITM Gwalior",
    "IIITDM Kancheepuram",
    "IIITDM Jabalpur",
    "IIITDM Kurnool",
    "IIIT Lucknow",
    "IIIT Guwahati",
    "IIIT Pune",
    "IIIT Kota",
    "IIIT Bhubaneswar",
    "IIIT Sri City",
    "IIIT Vadodara",
    "IIIT Nagpur",
    "IIIT Ranchi",
    "IIIT Kalyani",
    "IIIT Dharwad",
    "IIIT Kottayam",
    "IIIT Una",
    "IIIT Sonepat",
    "IIIT Senapati",
    "IIIT Bhopal",
    "IIIT Surat",
    "BITS Pilani",
    "VIT Vellore",
    "SRM Institute of Science and Technology",
    "Manipal Institute of Technology",
    "Thapar Institute of Engineering and Technology",
    "Amity University",
    "Shiv Nadar University",
    "Chandigarh University",
    "Lovely Professional University",
    "PES University",
];

export const registerRoles = [
    { value: "student", label: "Student" },
    { value: "researcher", label: "Researcher" },
    { value: "lab_assistant", label: "Lab Assistant" },
    { value: "professor", label: "Professor" },
];
